/*
 * (C) Copyright 2009-2016 ECMWF.
 * 
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
 * In applying this licence, ECMWF does not waive the privileges and immunities 
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.
 */

#ifndef DOCUMENTS_EXAMPLE_H_
#define DOCUMENTS_EXAMPLE_H_

// This file allows ExampleHeader.h to appear on the "Related Pages" part of
// the documentation generated by doxygen. This file contains no code, and does
// not appear in any cpp include statement.
//
/*!
 * \page ExampleHeader Example Header
 * \verbinclude Documents/ExampleHeader.h
 */
#endif  // DOCUMENTS_EXAMPLE_H_
