/*
 * (C) Copyright 2009-2016 ECMWF.
 * 
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
 * In applying this licence, ECMWF does not waive the privileges and immunities 
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.
 */

#ifndef DOCUMENTS_OVERVIEW_H_
#define DOCUMENTS_OVERVIEW_H_

// This file defines what appears on the "Related Pages" part of the
// documentation generated by doxygen. This file contains no code, and does
// not appear in any cpp include statement.
//
/*!
 * \page Overview Overview
 * This page is still under development!
 *
 * Over time, we aim to have a collection of documents that describe the
 * high-level structure of OOPS. Currently, we have the following:
 *
 *   <A HREF="../two_level_qg.pdf">A short description of the two-level
 *     quasi-geostrophic model</A>.
 *
 *   <A HREF="../weak_4dvar.pdf">Formulation of Weak Constraint 4D-Var</A>.
 *
 *   <A HREF="../solvers.pdf">Documentation of the OOPS Linear Equation
 *     Solvers</A>.
 *
 *
 */
#endif  // DOCUMENTS_OVERVIEW_H_
