codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        threshold: 0.05%
    patch:
      default:
        threshold: 2%

ignore:
  - "src/test"
  - "src/oops/contrib"
