#======================================================================
# Project settings
#======================================================================
branches:
  only:
    - develop

language: cpp

services:
  - docker

before_install:
  - date
  - REPO_SOURCE_DIR=${TRAVIS_BUILD_DIR}/jcsda/src_repo

#  create the same file structure on Travis VM and Docker container
  - mkdir -p ${TRAVIS_BUILD_DIR}/jcsda/src_repo
# echo branch info
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_BRANCH
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
#======================================================================
# Clone all repos
#======================================================================
  - git clone https://github.com/jcsda/oops-bundle.git ${REPO_SOURCE_DIR}/oops-bundle
  - cd ${REPO_SOURCE_DIR}/oops-bundle
  - git checkout $BRANCH || echo "No branch named $BRANCH in oops-bundle repo"
  - cd $REPO_SOURCE_DIR

  - git clone https://github.com/jcsda/fckit.git ${REPO_SOURCE_DIR}/oops-bundle/fckit
  - cd ${REPO_SOURCE_DIR}/oops-bundle/fckit
  - git checkout $BRANCH || echo "No branch named $BRANCH in fckit repo"
  - cd $REPO_SOURCE_DIR

#  checkout for the same branch name in atlas
  - git clone https://github.com/jcsda/atlas.git ${REPO_SOURCE_DIR}/oops-bundle/atlas
  - cd ${REPO_SOURCE_DIR}/oops-bundle/atlas
  - git checkout $BRANCH || echo "No branch named $BRANCH in atlas repo"
  - cd $REPO_SOURCE_DIR

#  clone the testing branch of oops
  - git clone -b $BRANCH https://github.com/jcsda/oops.git ${REPO_SOURCE_DIR}/oops-bundle/oops 

#  do no switch to develop branch by removing 
#  develop UPDATE in CMakeLists.txt in oops-bundle

  - cd ${REPO_SOURCE_DIR}/oops-bundle
  - sed -i 's/BRANCH develop UPDATE//' CMakeLists.txt
  - cat CMakeLists.txt
  - cd ${REPO_SOURCE_DIR}
  - ls ${REPO_SOURCE_DIR}
  - ls ${REPO_SOURCE_DIR}/oops-bundle
  - find . -name \* -exec chmod 777 {} \;

#======================================================================
# get docker image
# FROM  jcsda/docker:latest
#======================================================================
  - cd ${REPO_SOURCE_DIR}/oops-bundle/oops
  - date
  - docker build -t jcsda/dockerl2 --build-arg=Dockerfile .  #Dockerfile handles ssh for mpi
  - date
  - docker images
# request codecov to detect CI environment to pass through to docker
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run -d -t $ci_env --name jcsda_container -v ${REPO_SOURCE_DIR}/oops-bundle:/jcsda/src_repo jcsda/dockerl2
  - docker ps -a
  - date

#======================================================================
# Here are the run steps
#======================================================================
script:
  - docker exec jcsda_container ls
  - docker exec jcsda_container bash -c 'cp -r /jcsda/.openmpi/ ~/' 
##  use cmake with flags to generate test coverage reports
  - date
  - docker exec jcsda_container bash -c 'cd /build_container && cmake -DCMAKE_MODULE_PATH=/usr/local/share/ecbuild/cmake/ -DCMAKE_BUILD_TYPE=Debug -DENABLE_GPROF=ON  /jcsda/src_repo'
  - date
  - docker exec jcsda_container bash -c 'cd /build_container/oops && make -j4'
  - date
  - docker exec jcsda_container bash -c 'cd /build_container/oops && ctest'
  - date
##  run lcov inside container
  - docker exec jcsda_container bash -c 'cd /build_container/oops && lcov --capture --directory . --output-file coverage.info'
  - docker exec jcsda_container bash -c 'cd /build_container/oops && lcov --remove coverage.info "/usr/*" --output-file coverage.info'  #  filter system-files 
  - docker exec jcsda_container bash -c 'cd /build_container/oops && lcov --list coverage.info'  #  debug info
  - docker exec jcsda_container bash -c 'cd /build_container/oops && bash <(curl -s https://codecov.io/bash) -t 3b511d7d-c15d-4ee5-8a1e-29c6d97d2032  -X gcov -f coverage.info -R /jcsda/src_repo/oops/'
