#======================================================================
# Project settings
#======================================================================
env:
  global:
  - secure: ztTCO/DzSfshSaPMJ6BzySkaD2TSeAITKUFaMYbJ7fUWn9bYSDGzxXI90jpusAn7r2Z6exQC0kGfgIWwqVnAhTed9kBk+vyeskB6lsGdpJ1EGjtxhPKiAITIMuwEhmfaqBmuC20f8UkClpxEPmYEYxBR0wamAIQ4FAe/1QGdYZ+uEbNYKbjcyPCZNe/A/xeOYIjo88urY3jCNfFH1DShgEXV+GhbQl/nNSgSGp4n2u8ay5IVr7dzh/NG51y77D43p8e0Rqd255uDt7hro+6O7XakDLjABmkO2fTs6+osmRqHOOSbv3fLz7O1dcdHVDFPI7U7u6GZX6dCwuvRAWi/l62MqJ//+tXpLr81AyH75eoMHovbMdbkkbftrcCqXTIMLoqt3hZ0XQtiYv0+aOKb/67l09UNz1szSImhxiFxNB7SfK6vVmJ0vzqB835NCIbxpW0iJuVRxBNIssd9oU+9wvaBCpGUxJBL/anoxEGhFt4olmewVZzCbiwCuFlp8cZAFwUVNXnGah87QZW76KD+qaDHWaWYp6KzdBmLeWFu5hBOBIGVSEZyxeAgMUyOi8fYfsw2q/dGLPryXfLALEui1uN4XOwAuOGnmqecqXOpaFeRIhJbc03JizxdISteRQRdYXshYgeM7/9VPXyYhzg2Z8sijvbY7MBZwTtEPipXkNM=
  - secure: a7T55NgRK0dmjPb+5vddqpXuAwJ9l/VNCbFlisVG7uYrmfeIybNwE2rTxU4wTy3GX+mjB8VjsxtjPk5jutA16Xb/8tg3EzLn6VHpA2uHVlzap0PAaPLnvpTKvRtYa0J/AJr4GPLV69Dnl022h8LdBNVXqIVoYZPEv2R27BvVZAN2TFucCSXKZXYUW/fpMZdbe++45V9UDGTBEoq+csyesM6ent2fp4dSmuTxXVzOW4VEeBD3MxKwYaEz7Ay4nDvi1EqLtXb8sQIPC+PCRrQobLXTML7aeDiwHDnYK5m74rc0BHaUz6syJTh4eBL6mjvB4d3bcX+Y5tLLkV6fMKr44L382bK/zayxOpfAKpyxaWQwnomkw7RMisLaDNCACxl/7yQkRnj5tZO2HbXuMZH3MO7WWeZaLtV28bj4ZbWAVLWRqgGb1paA0jKqEMtylzfekRSFXg995qvTJCnzkfO9lkG/agXp/ljbYqc8Ts54EqvjdlR6PvUkWJZCAOcXiUw1rNKq9k4czNsyzpM0xwzguNs9HYThKIDwxBDg/8vsISO4Gt8JYnVOk+JMXxqtyFmnzdu7E3vB02QSZsdNvipRrPwZ+rcM6qiwfMFejt5eayG2ow5rYU0BPN0BLWYv8b0kpZP2e6o9+8qSEmxQ7tm7R7RDOQEv4RviKD4F/GoJmtE=
  - secure: S6E4UYFyTAQP19KEYT9r08O+yPJIquX5kITqKsj04N7q6smuEoKv6lletWpqhMcZtWdfsV49LvmU5XgGLj3jNTiU0GsBJYl7H0cF3E4/3QQgK7Qm1gbxmd50odQXloi1UXaMVprgixD/TFroPhyE2IsaV/TxuBdJIL732wRt+I2qzhrYbbK4DqFPjKqxXHQgwLVc9ZbmaZLHSf/WQ4IaYLtT7d6ChvZvxkbLlf3/V2OpKo85VwPk1oLdVCL9GbZSKqMFPpliOg2PoZCaAz9To5dAcbWoKEDKOVaf0DwUVgbjshZWeXvbVYRqxp5NeS4xmL2+7FdgfzAcfhWLMfZrYAN+0SmTjS+6F3+WSVF90bkPzORJTyga28LtN5zV8H6Dc4YkYGlotjTIdgH5a/p5DooQ0K87fF7JItypt7TuaVHxM7oy5vTCy0xghJD5lJ8JTy7NfCmGncK+Dh3GdhWCDVSCRspL62dqu8UX7Ekz0+x0HHkAL0ZhswzCTiEZoQFXIhAsJw8BA+YRAmHBGG4fpEqJlq1EjDm9Ca9AHBRvf1f4npM12znBhhjF/e7JSVOHgbDP9YrvZWLRC8YWuFcOaRZU3JtrG1bbCDtZXJ4UK4gQv7Ru5rbtVk/q6d56qaMvC//6RFYxSYxpA+WD8Crcb/OsK3eKHrOzgsbtm1PYCRM=
branches:
  only:
    - develop

language: cpp

services:
  - docker

before_install:
  - date
  - REPO_SOURCE_DIR=${TRAVIS_BUILD_DIR}/jcsda/src_repo

#  create the same file structure on Travis VM and Docker container
  - mkdir -p ${TRAVIS_BUILD_DIR}/jcsda/src_repo
# echo branch info
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_BRANCH
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

  - cd CI
  - REPO_SOURCE_DIR=${TRAVIS_BUILD_DIR}/jcsda/src_repo
  - git clone https://${GH_TOKEN}@github.com/jcsda-internal/jedi-build-package.git ${REPO_SOURCE_DIR}/jedi_build_package

  - docker pull jcsda/docker-clang-mpich-dev
  - docker images
script:
  - docker run -d -t --env GH_TOKEN=$GH_TOKEN --env AWS_ACCESS_KEY_ID=$aws_access_key_id --env AWS_SECRET_ACCESS_KEY=$aws_secret_access_key --env GH_BRANCH=$BRANCH --name clang_container -v ${REPO_SOURCE_DIR}/jedi_build_package:/jcsda/src_repo jcsda/docker-clang-mpich-dev

  - docker exec clang_container bash -c 'mkdir ~/.aws'
  - docker exec clang_container bash -c 'echo [default] >> ~/.aws/credentials '
  - docker exec clang_container bash -c 'echo aws_access_key_id = $aws_access_key_id >> ~/.aws/credentials'
  - docker exec clang_container bash -c 'echo aws_secret_access_key = $aws_secret_access_key >> ~/.aws/credentials'
  - docker exec clang_container bash -c 'ls /jcsda/src_repo'
  - docker exec clang_container bash -c 'cd /jcsda/src_repo && pip install --user -e .'

  - docker exec clang_container bash -c 'cd /jcsda/src_repo && ~/.local/bin/jedi-build --gh-token=$GH_TOKEN -j 4 --env-id=docker-clang --branch-map atlas:release-stable fckit:release-stable -br ${GH_BRANCH} -p oops -vvv -3 -u --submit-dashboard --site TravisCI --abort-on-build-errors --abort-on-test-errors'
