version: 0.2

env:
  parameter-store:
    GIT_USER: "/CodeBuild/Git_USER"
    GIT_PASS: "/CodeBuild/Git_PASS"

phases:
  install:
    commands:
      - echo Executing install phase
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CODEBUILD_WEBHOOK_BASE_REF
      - echo $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID
      - echo $CODEBUILD_WEBHOOK_EVENT
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION

      - pwd
      - ls
      - git rev-parse --abbrev-ref HEAD
      - push_branch="$(git rev-parse --abbrev-ref HEAD)"
      - echo $push_branch

      - if [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_MERGED" ];
        then export CODEBUILD_GIT_BRANCH="develop";
        echo "Merging to develop";
        else CODEBUILD_GIT_BRANCH="$(git branch -a --contains $CODEBUILD_RESOLVED_SOURCE_VERSION | sed -n 2p | awk '{ printf $1 }')";
        export CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH#remotes/origin/};
        fi

      - echo "CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH}"
      - echo "CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION}"

  pre_build:
    commands:
      - echo Executing pre_build phase
      - mkdir /build_container
      - mkdir /jcsda

      - git lfs install
 
      # oops-bundle
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/oops-bundle oops-bundle
      - cd oops-bundle
      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in oops-bundle repo"
      - cd $CODEBUILD_SRC_DIR
      - ls

      # oops
      - git clone -b $CODEBUILD_GIT_BRANCH https://$GIT_USER:$GIT_PASS@github.com/jcsda/oops oops-bundle/oops
      - ls

      # fckit
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/fckit oops-bundle/fckit
      - cd oops-bundle/fckit
      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in fckit repo"
      - cd $CODEBUILD_SRC_DIR
      - ls

      # disable git-lfs
      - git lfs install --skip-smudge

      # atlas
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/atlas oops-bundle/atlas
      - cd oops-bundle/atlas
      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in atlas repo"
      - cd $CODEBUILD_SRC_DIR
      - ls
     
      - mv oops-bundle /jcsda/
      - cd /jcsda/oops-bundle
      - ls
      - sed -i 's/BRANCH develop UPDATE//' CMakeLists.txt
      - sed -i '/PROJECT eckit/d' CMakeLists.txt

  build:
    commands:
      - echo Executing build phase
      - cd /build_container 
      - ls
      - ecbuild /jcsda/oops-bundle/
      - cd oops
      - make -j4

      - export BUILD_STATUS="0"
      - echo $BUILD_STATUS
      - echo $CODEBUILD_BUILD_SUCCEEDING

      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ];
        then export BUILD_STATUS="1";
        echo "Build passed";
        fi
      - echo $BUILD_STATUS

      - cd /build_container/oops 
      - ctest
  
  post_build:
    commands:
      - echo Executing post_build phase
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - if [ "$BUILD_STATUS" = "1" ] && [ "$CODEBUILD_BUILD_SUCCEEDING" = "0" ];
        then echo "Build passed, rerun failed tests";
        cd /build_container/oops;
        ctest -VV --rerun-failed;
        fi
