version: 0.2

env:
  shell: bash
  parameter-store:
    GIT_USER: "/CodeBuild/Git_USER"
    GIT_PASS: "/CodeBuild/Git_PASS"

phases:
  install:
    commands:
      - echo Executing install phase
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo $CODEBUILD_SOURCE_VERSION

      - echo $CODEBUILD_WEBHOOK_MERGE_COMMIT
      - echo $CODEBUILD_WEBHOOK_PREV_COMMIT
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID
      - echo $CODEBUILD_WEBHOOK_EVENT
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CODEBUILD_WEBHOOK_BASE_REF

      - gh_source=$(pwd)
      - echo ${gh_source}
      - echo $CODEBUILD_SRC_DIR

      # Codebuild only runs on PUSH events if HEAD_REF
      # is refs/heads/develop (merge to develop). In this
      # case CODEBUILD_GIT_BRANCH="develop"

      - if [ "$CODEBUILD_WEBHOOK_EVENT" = "PUSH" ];
        then export CODEBUILD_GIT_BRANCH="develop";
        echo "Merging to develop";
        else export CODEBUILD_GIT_BRANCH=${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/};
        fi

      - echo "CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH}"
      - echo "CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION}"

      - echo "check for same branch names, except for develop"
      - if ! [ "$CODEBUILD_GIT_BRANCH" = "develop" ]; then
        pip install boto3;
        pip install pygithub;
        python CI/update_webhook_branchname.py $CODEBUILD_GIT_BRANCH $CODEBUILD_RESOLVED_SOURCE_VERSION;
        fi

  build:
    commands:
      - echo Executing build phase
      - mkdir artifacts
      - echo ${CODEBUILD_GIT_BRANCH} > artifacts/branch_name.txt
      - echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} > artifacts/commit_sha.txt

      # get jedi-build-package
      - git clone -b feature/ecbuild35 https://$GIT_USER:$GIT_PASS@github.com/jcsda-internal/jedi-build-package

      - cd jedi-build-package
      - pip install --user -e .

      - ~/.local/bin/jedi-build --gh-token=$GIT_PASS -j 4 --env-id=docker-clang --branch-map atlas:release-stable fckit:release-stable -br ${CODEBUILD_GIT_BRANCH} -p oops -vvv -3 -u --submit-dashboard --site CodeBuild --abort-on-build-errors --abort-on-test-errors --cleanup=False 2>&1 | tee jedi_build_output.txt ; test ${PIPESTATUS[0]} -eq 0

      #find CDASH URL
      - Done_path_line=$(grep 'Done.xml' jedi_build_output.txt | tail -1)
      - echo $Done_path_line
      - Done_path=$(echo ${Done_path_line} | sed 's/Uploaded://')
      - echo $Done_path
      - cat $Done_path
      # retrieve buildID from Done.xml
      - buildID=$(cat $Done_path | grep -o -P '(?<=buildId>).*(?=</build)')
      - echo ${buildID}
      - url=https://cdash.jcsda.org/buildSummary.php?buildid=${buildID}
      - echo ${url}

      #create artifacts
      - mkdir -p /jcsda/artifacts/
      - echo ${url} > /jcsda/artifacts/cdash-url.txt
      - cat /jcsda/artifacts/cdash-url.txt
      - echo ${CODEBUILD_GIT_BRANCH} > /jcsda/artifacts/branch_name.txt
      - echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} > /jcsda/artifacts/commit_sha.txt
      - ls  /jcsda/artifacts/

artifacts:
  files:
    - '/jcsda/artifacts/*'
  name: oops-clang-url
