version: 0.2

env:
  parameter-store:
    GIT_USER: "/CodeBuild/Git_USER"
    GIT_PASS: "/CodeBuild/Git_PASS"

phases:
  install:
    commands:
      - echo Executing install phase

      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_REPO_URL
      - org_name=$(echo $CODEBUILD_SOURCE_REPO_URL | awk '{split($0,org,"/"); print org[4]}')
      - echo $org_name
      - echo $CODEBUILD_SOURCE_VERSION

      - echo $CODEBUILD_WEBHOOK_MERGE_COMMIT
      - echo $CODEBUILD_WEBHOOK_PREV_COMMIT
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID
      - echo $CODEBUILD_WEBHOOK_EVENT
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CODEBUILD_WEBHOOK_BASE_REF

      # Codebuild only runs on PUSH events if HEAD_REF
      # is refs/heads/develop (merge to develop). In this
      # case CODEBUILD_GIT_BRANCH="develop"

      - if [ "$CODEBUILD_WEBHOOK_EVENT" = "PUSH" ];
        then export CODEBUILD_GIT_BRANCH="develop";
        echo "Merging to develop";
        else export CODEBUILD_GIT_BRANCH=${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/};
        fi

      - echo "CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH}"
      - echo "CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION}"

  pre_build:
    commands:
      - echo Executing pre_build phase
      - mkdir -p /jcsda/oops-bundle

      - git lfs install
      - cp ~/.gitconfig /home/jedi/
      - cd CI

      - if [ "$CODEBUILD_GIT_BRANCH" = "develop" ];
        then export CODEBUILD_GIT_BRANCH_FORK="release-stable";
        else export CODEBUILD_GIT_BRANCH_FORK=${CODEBUILD_GIT_BRANCH};
        echo "CODEBUILD_GIT_BRANCH_FORK=${CODEBUILD_GIT_BRANCH_FORK}";
        fi

      # Upload branch name and commit sha as CodeBuild artifact to S3
      - mkdir /jcsda/artifacts
      - echo ${CODEBUILD_GIT_BRANCH} > /jcsda/artifacts/branch_name.txt
      - echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} > /jcsda/artifacts/commit_sha.txt

      # oops
      - ./clone.sh $GIT_USER $GIT_PASS jcsda-internal/oops $CODEBUILD_GIT_BRANCH oops /jcsda/oops-bundle develop
      # fckit
      - ./clone.sh $GIT_USER $GIT_PASS jcsda-internal/fckit $CODEBUILD_GIT_BRANCH_FORK fckit /jcsda/oops-bundle release-stable
      # atlas
      - ./clone.sh $GIT_USER $GIT_PASS jcsda-internal/atlas $CODEBUILD_GIT_BRANCH_FORK atlas /jcsda/oops-bundle release-stable


      # move CMakeLists.txt from oops/CI to bundle directory
      - cp CMakeLists.txt /jcsda/oops-bundle/CMakeLists.txt

      # cdash upload setup
      - mkdir /jcsda/oops-bundle/cmake
      - cp cmake/CTestCustom.ctest.in /jcsda/oops-bundle/cmake/
      - cp cmake/cdash-integration.cmake /jcsda/oops-bundle/cmake/
      - cp cmake/CTestConfig.cmake /jcsda/oops-bundle/

  build:
    on-failure: CONTINUE
    commands:
      - echo Executing build phase
      - export BUILD_STATUS="0"
      - echo $BUILD_STATUS
      - echo $CODEBUILD_BUILD_SUCCEEDING

      # configure and build
      - su - jedi -c "cd /home/jedi
        && ls
        && export FC=mpifort
        && export CC=mpicc
        && export CXX=mpicxx
        && ecbuild -Wno-dev -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCDASH_OVERRIDE_GIT_BRANCH=$CODEBUILD_GIT_BRANCH -DCTEST_UPDATE_VERSION_ONLY=FALSE -DENABLE_GPROF=ON /jcsda/oops-bundle/"

      - su - jedi -c "cd /home/jedi/oops
        && export FC=mpifort
        && export CC=mpicc
        && export CXX=mpicxx
        && cp ../DartConfiguration.tcl .
        && sed -i 's/oops-bundle/oops-bundle\/oops/' DartConfiguration.tcl
        && sed -i 's/jedi/jedi\/oops/' DartConfiguration.tcl
        && cat DartConfiguration.tcl
        && make -j4"

      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ];
        then export BUILD_STATUS="1";
        echo "Build passed";
        fi
      - echo $BUILD_STATUS

      # run ctest and upload to cdash
      - su - jedi -c "cd /home/jedi/oops
        && export FC=mpifort
        && export CC=mpicc
        && export CXX=mpicxx
        && ctest -C RelWithDebInfo -D ExperimentalTest -E test_qg_4dvar_saddlepoint"

    finally:
       - su - jedi -c "cd /home/jedi/oops
        && export FC=mpifort
        && export CC=mpicc
        && export CXX=mpicxx
        && ctest -C RelWithDebInfo -D ExperimentalSubmit -M Continuous -- --track Continuous --group Continuous"

  post_build:
    commands:
      - echo Executing post_build phase
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - echo $BUILD_STATUS

      # upload find cdash url and upload it as CodeBuild artifact to S3
      - if [ "$BUILD_STATUS" = "1" ];
        then echo "Build & tests passed, find cdash url";
        bash /jcsda/oops-bundle/oops/CI/cdash-url.sh /home/jedi/oops/Testing;
        url=$(bash /jcsda/oops-bundle/oops/CI/cdash-url.sh /home/jedi/oops/Testing);
        echo $url;
        echo ${url} > /jcsda/artifacts/cdash-url.txt;
        cat /jcsda/artifacts/cdash-url.txt;
        else echo "Build failed";
        fi

      - echo 'Connect to CodeCov'
      - cd /home/jedi/oops
      - pwd
      - ls
      - bash /jcsda/oops-bundle/oops/CI/codecov_script_$org_name.sh

artifacts:
  files:
    - '/jcsda/artifacts/*'
  name: oops-gnu-url
