datadir: '$(experiment_dir)/{{current_cycle}}'
date: '{{current_cycle}}'
filename: $(experiment_dir)/{{current_cycle}}/$(experiment).fc.{{current_cycle}}.${step}.nc
exp: $(experiment)
frequency: PT3H
type: fc
