#pragma once

// This file defines what appears on the Main Page of the documentation
// generated by doxygen. The file contains no code, and does not appear
// in any cpp include statement.
//
/*!
 * \mainpage Object Oriented Prediction System (OOPS)
 *
 * OOPS is the top level of JEDI that orchestrates the configuration and execution of applications. This is where DA applications are implemented. OOPS also includes the Lorenz 95 and Quasi-geostrophic toy models that can used to run many of the DA applications.
 */
