#!/bin/bash
set -euxo pipefail
repo="$1"  # expect path to a repo clone

branch_name="${GITHUB_HEAD_REF}"
if [[ "${branch_name}" == 'develop' ]]; then
    exit
fi

# Attempt to checkout a branch from a dependency project with the same name as
# the branch triggering this GitHub Actions workflow.
cd "${repo}"
if git fetch --progress --depth=1 origin \
    "+refs/heads/${branch_name}:refs/remotes/origin/${branch_name}"
then
    git checkout --progress --force -B "${branch_name}" \
        "refs/remotes/origin/${branch_name}"
fi

exit
