---
name: UKMO-CI-Az

on:
  pull_request:
    branches: [develop]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}


jobs:
  build-and-test:
    if: github.repository_owner == 'JCSDA-internal'
    name: gnu 11.3.1 (UKMO)
    runs-on: jedi-self-hosted-ext
    steps:
      - name: pre-submit cleanup
        run: |
          ls -la ./
          rm -fr ./CI || true
          ls -la ./
      - name: checkout current
        uses: actions/checkout@v3
        with:
          path: CI/meto/oops
          repository: JCSDA-internal/oops

      - name: initiate bundle
        working-directory: CI/meto
        run: ln -sf oops/CI/meto/* .

      - name: checkout jedicmake
        uses: actions/checkout@v3
        with:
          path: CI/meto/jedicmake
          repository: JCSDA/jedi-cmake
          submodules: true

      - name: build and test
        run: |
          az acr login --name ngmssboxjediacr
          docker run --rm \
            --env OMPI_ALLOW_RUN_AS_ROOT=1 \
            --env OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
            --env OMPI_MCA_rmaps_base_oversubscribe=1 \
            --entrypoint=/usr/local/src/oops-ci/build-and-test \
            --workdir=/usr/local/src/oops-ci/ \
            --volume $PWD/CI/meto:/usr/local/src/oops-ci \
            'ngmssboxjediacr.azurecr.io/jedibase:gnu-11.3.1'

      - name: Cleanup workspace
        working-directory: ${{github.workspace}}
        run: rm -fr CI || true
