---
name: UKMO-CI-Az

on:
  pull_request:
    branches: [develop]

jobs:
  build-and-test:
    if: github.repository_owner == 'JCSDA-internal'
    runs-on: jedi-self-hosted-ext
    steps:
      - name: pre-submit cleanup
        run: |
          ls -la ./
          rm -fr ./CI || true
          ls -la ./
      - name: checkout current
        uses: actions/checkout@v3
        with:
          path: CI/meto/oops
          repository: JCSDA-internal/oops

      - name: initiate bundle
        working-directory: CI/meto
        run: ln -sf oops/CI/meto/* .

      - name: checkout jedicmake
        uses: actions/checkout@v3
        with:
          path: CI/meto/jedicmake
          repository: JCSDA/jedi-cmake
          submodules: true

      - name: build and test
        run: |
          az acr login --name ngmssboxjediacr
          docker run --rm \
            --entrypoint=/usr/local/src/oops-ci/build-and-test \
            --workdir=/usr/local/src/oops-ci/ \
            --volume $PWD/CI/meto:/usr/local/src/oops-ci \
            'ngmssboxjediacr.azurecr.io/jedibase:alma9' && \
          rm -fr ${{github.workspace}}/CI
